Additional checks for brew

diff --git a/home/.chezmoiscripts/run_onchange_before_common_01-install-homebrew.sh.tmpl b/home/.chezmoiscripts/run_onchange_before_common_01-install-homebrew.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_before_common_01-install-homebrew.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_before_common_01-install-homebrew.sh.tmpl
@@ -7,12 +7,17 @@ exit 0
 
 set -e
 
-if [ -x ${BREW_PATH} ]; then
-  eval "$(${BREW_PATH} shellenv)"
-  if command -v brew; then
-    echo "Brew already installed"
-  else
-    echo "Installing Homebrew"
-    which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-  fi
+echo "Brew Path: ${BREW_PATH}"
+
+if [[ -z ${BREW_PATH} ]]; then
+  echo "Error: Homebrew path not set. Exiting."
+  exit 1
+fi
+
+eval "$(${BREW_PATH} shellenv)"
+if command -v brew; then
+  echo "Brew already installed"
+else
+  echo "Installing Homebrew"
+  which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 fi
